### ISSUE TITLE
Getting compile time error in HTML.java

### ISSUE THREAD

**Issue by gurungmukund** [mwilliamson/dotnet-mammoth#10]
Downloaded the zip from https://github.com/mwilliamson/java-mammoth and trying to run but getting compile time error in HTML.java in following lines of code

The method getChildren() is undefined for the type Object	Html.java	/mammoth/src/main/java/org/zwobble/mammoth/internal/html	line 144	Java Problem

The method getChildren() is undefined for the type Object	Html.java	/mammoth/src/main/java/org/zwobble/mammoth/internal/html	line 147	Java Problem

The method isMatch(HtmlElement, HtmlElement) in the type Html is not applicable for the arguments (Object, HtmlElement)	Html.java	/mammoth/src/main/java/org/zwobble/mammoth/internal/html	line 141	Java Problem

Type mismatch: cannot convert from Optional<HtmlElement> to Optional<Object>	Html.java	/mammoth/src/main/java/org/zwobble/mammoth/internal/html	line 138	Java Problem

**Comment by mwilliamson** [comment]
This looks like an issue with the Java implementation of Mammoth, for which it looks like you've already made an issue, so closing this one.
