### ISSUE TITLE
Suppress <img stream data

### ISSUE THREAD

**Issue by RustyE** [mwilliamson/dotnet-mammoth#12]
Is there a way to (in the .NET version) suppress inclusion of the entire image file within the HTML?
I would like it to include only an <img src="c:/folder/filename" alt="" ...    With no raw image data.
If so, how does one accomplish this?  (An example in C# or VB would be helpful)
Thanks

**Comment by mwilliamson** [comment]
You can use a [custom image handler](https://github.com/mwilliamson/dotnet-mammoth#custom-image-handlers) to change how images are handled.

**Comment by RustyE** [comment]
Thank you Michael,
I can’t understand the code shown on that URL.
Is there any chance you could provide a C#/VB example?
Thanks for your kind response.
Regards,
Rusty
