### ISSUE TITLE
Custom Font Usage

### ISSUE THREAD

**Issue by JamshidJD** [mwilliamson/dotnet-mammoth#13]
I really loved using mammoth, and the way is converts the docx into clear html. My problem is i'm using some custom fonts and they are not being converted to HTML. can you help me how to enable custom fonts for conversion of documents.
Thank you.

**Comment by mwilliamson** [comment]
The recommended approach would be to use a Word style in your document to set the font, and then to map that Word style to a CSS class that applies the same font.
