### ISSUE TITLE
Convert to html, and the checkbox cannot be displayed.

### ISSUE THREAD

**Issue by bbhxwl** [mwilliamson/dotnet-mammoth#14]
Convert to html, and the checkbox cannot be displayed.

Other conversion software can display different characters.

**Comment by mwilliamson** [comment]
Sorry, I'm not sure I understand the issue you're describing. Since this is quite an old issue, I'm going to close this due to lack of information, but if this is still a problem, it would be helpful to have a minimal example document, the expected HTML, and the actual HTML you're getting.
