### ISSUE TITLE
Custom mapping for <a> to <span>

### ISSUE THREAD

**Issue by Laftek** [mwilliamson/dotnet-mammoth#15]
Hi there,

Firstly, great job it works like a charm :)

I am trying to convert `<a>` to `<span>` to avoid linking. I tried the code below but I am getting error. I tried multiple combinations but still the same error.
```
var converter = new DocumentConverter()
                        .AddStyleMap("a => span");
```
Console error:
```
error reading style map at line 1, character 1: Unrecognised document element: Mammoth.Couscous.org.zwobble.mammoth.internal.styles.parsing.Token`1[Mammoth.Couscous.org.zwobble.mammoth.internal.styles.parsing.TokenType]
blazor.webassembly.js:1 
blazor.webassembly.js:1 a => span
blazor.webassembly.js:1 ^
```

Could you please help with this issue?

Thank you.

**Comment by mwilliamson** [comment]
I'm afraid style mappings aren't supported for links. Your best bet is probably to post-process the generated HTML.

**Comment by Laftek** [comment]
Thank you for the prompt answer! I needed to know if I am doing something wrong. Thanks again :)
