### ISSUE TITLE
Read form memory and not from a physics path

### ISSUE THREAD

**Issue by NicklasOestergaard** [mwilliamson/dotnet-mammoth#16]
I love this little program/tool, but I'd like to know if it's possible to clean and convert a word document without having a physical path to the file.

**Comment by mwilliamson** [comment]
I believe you should also be able to pass in a `Stream`.

**Comment by NicklasOestergaard** [comment]
Sorry to ask, but I really can't get it to work. Is it possible to see or get a reference to an example?
