### ISSUE TITLE
Information/Question about the future of this package

### ISSUE THREAD

**Issue by r-Larch** [mwilliamson/dotnet-mammoth#17]
Hi,

Since the repository has not been updated for some time and lacks a .NET Core build, I have created a fork to offer a `nuget` package that is compatible with .NET Core `net8.0`. This fork not only transitions your work to .NET Core but also upgrades the `generated.cs` to java-mammoth v1.7.0.

Should you wish to continue maintaining your work, I am willing to provide a pull request with my modifications. The .NET Core port is easily configurable to target the older .NET Framework and .NET Standard, ensuring support for all legacy .NET versions, in the case it is required. Additionally, it includes functioning GitHub actions for building, testing, and publishing the code on `nuget.org`.

I have released my build on nuget under the name `LarchSys.WordToHtml`. If you opt to resume maintenance of the repository, you might consider using `Mammoth.WordToHtml` as the package name. I chose the prefix `LarchSys` to ensure the `Mammoth` prefix remains available.

Fork: [dotnet-mammoth-core](https://github.com/r-Larch/dotnet-mammoth-core)

Best regards,
René Larch

**Comment by mwilliamson** [comment]
Hello René! Thanks for working on this. As it happens, I've actually just been working on the same thing myself. I've uploaded a new version, 1.7.0-alpha.2, to NuGet, which I fondly believe targets .NET Standard 2.0, if that works for you?

Sorry for the duplication of effort! I'm impressed that anyone was brave enough to work through the horrors of how the project works.

**Comment by r-Larch** [comment]
Hello @mwilliamson ,

after writing this issue I saw your commits 😅
.NET Standard could work, but in terms of performance I would like to have a `net8.0` target because loading .NET Standard libs always had a performance impact (I don't know if this stays true today as the .NET runtime improves rapidly).

Would you accept a PR to support multi-targets for `netstandard2.0` and `net8.0`?
Theoretically, it would be a one-line change plus configuring tests to run against all targets.

Note: 
you could add this nuget version badge on top of the README.md: ![NuGet Version](https://img.shields.io/nuget/v/Mammoth)
```md
![NuGet Version](https://img.shields.io/nuget/v/Mammoth)
```
This link would direct you to the `Mammoth` NuGet package version,
making it easier for someone like you to find the package. 😉

**Comment by mwilliamson** [comment]
I'm not necessarily opposed to multi-targets, but if the reason is performance, it'd be good to see some comparisons of Mammoth's performance in practice before adding support.

**Comment by r-Larch** [comment]
Regarding .NET Standard performance I could find this:
[Separating the API set from its implementation doesn’t just slow down the availability of APIs. It also means [...]](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/#:~:text=Separating%20the%20API%20set%20from%20its%20implementation%20doesn%E2%80%99t%20just%20slow%20down%20the%20availability%20of%20APIs)

For this project, I believe the performance impact would be negligible, so targeting netstandard2.0 alone should suffice. However, including a target for the latest LTS version, such as `net8.0`, might offer some advantages.

Additionally, I'd like to express my gratitude for your excellent work! The mammoth project has been incredibly useful, and the couscous project is quite fascinating. The concept of automatically porting code across various languages is appealing!

**Comment by mwilliamson** [comment]
> For this project, I believe the performance impact would be negligible, so targeting netstandard2.0 alone should suffice. However, including a target for the latest LTS version, such as `net8.0`, might offer some advantages.

That's good to know: if there are specific reasons to also target other platforms, performance or otherwise, but in the meantime I thing just targeting .NET Standard 2.0 helps to keep things simple.

> Additionally, I'd like to express my gratitude for your excellent work! The mammoth project has been incredibly useful

No worries, I'm glad you've found it useful!

> and the couscous project is quite fascinating. The concept of automatically porting code across various languages is appealing!

Yeah, it's certainly not something I'd advocate doing, but it was at least interesting to do (which was the main motivation!)

If you get a chance to try out the prerelease version on NuGet, I'd be interested to hear whether it works for you or not.
