### ISSUE TITLE
Word Online: Missing entry in file: word/document.xml

### ISSUE THREAD

**Issue by JohnGalt1717** [mwilliamson/dotnet-mammoth#2]
Hi there.

Any document created by Word Online and not saved in the desktop word yet results in the above error if you download the file and run it through Mammoth.

As soon as you save in the desktop application it works just fine.

**Comment by mwilliamson** [comment]
Sounds like the files from Word Online aren't saved in the same format. Could you provide an example document?

**Comment by JohnGalt1717** [comment]
[tmp2BA8.docx](https://github.com/mwilliamson/dotnet-mammoth/files/1315249/tmp2BA8.docx)

Here's one that should have content.

**Comment by mwilliamson** [comment]
Looks like the ZIP is indeed laid out differently. From a quick glance, it looks like `_rels/.rels` stores the location of the document. I'm not sure when I'll get a chance to look at this myself though.

**Comment by JohnGalt1717** [comment]
Ok. Thanks. My work around thus far is to simply copy in a word doc that was saved in the desktop app and rename it (using Microsoft.Graph) which seems to work fine.

Was just hoping it was an easy fix.

**Comment by mwilliamson** [comment]
This should be fixed in 1.4.0, shout if not.
