### ISSUE TITLE
The link cannot be successfully converted

### ISSUE THREAD

**Issue by SweelLong** [mwilliamson/dotnet-mammoth#20]
I know that the underlining of any text is ignored since underlining can be confused with links in HTML documents.
Although I try to display the underline by the method **AddStyleMap("u => em")**, I still cannot see the link function being used!
As we can see here: 
The link text was written in *.docx file, I can right click it andchoose to open the website!
![70cf6d0222252d691c1316e8460c24fd](https://github.com/mwilliamson/dotnet-mammoth/assets/64245640/3616ad44-fefc-4985-acdd-f3553526bf3b)
![image](https://github.com/mwilliamson/dotnet-mammoth/assets/64245640/aa615d60-9b6f-4dcb-9ba8-e56737381729)
And then I convert the *.docx file to *.html file. When I delightedly open the new file(html file) , I just could see the simple text and its html code was made up of < p > !
![image](https://github.com/mwilliamson/dotnet-mammoth/assets/64245640/6ec4e81c-4475-4c59-83d2-0ef264c078f7)

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML you'd expect to see, and the HTML you're actually seeing?

**Comment by SweelLong** [comment]
Sorry, I eventually found that is my fault !
But I still want to express my sincere gratitude for your help and your useful project !
