### ISSUE TITLE
.Net Standard version

### ISSUE THREAD

**Issue by rchinni-rythmos** [mwilliamson/dotnet-mammoth#3]
This utility works great. 
Any plans to release a .Net Standard version of this?
OR
if we would like to do the port ourselves, do you foresee any compatibility issues

**Comment by mwilliamson** [comment]
I haven't done any .NET development (other than this project) in a couple of years, so the honest is: I have no idea! I haven't kept up with .NET Standard, .NET Core and whatever else there is, so can't really say anything useful about them.

**Comment by niteshrestha** [comment]
Ran it through .NET Portability Analyzer and it says there shouldn't be any issue with it.
Should I go ahead and port it?
![image](https://user-images.githubusercontent.com/4751915/71716936-78566780-2e3e-11ea-9d66-47f404b8fa8f.png)

**Comment by ghost** [comment]
In case this is still relevant: https://docs.microsoft.com/en-us/dotnet/core/porting/

**Comment by max-carroll** [comment]
I am considering porting this to .net Core as I all my C# stuff is in .net Core so I cant use this in its current state

**Comment by mwilliamson** [comment]
I've just uploaded 1.7.0-alpha.2 to NuGet, which uses .NET Standard 2.0. Since I don't actually use the library myself, reports of whether it works or not are gratefully received!

**Comment by manzanotti** [comment]
Sorry for the delay, but this is now on our production server, and works fine.

**Comment by mwilliamson** [comment]
Thanks for letting me know!

**Comment by mwilliamson** [comment]
I've now released 1.8.0 for .NET Standard 2.0.
