### ISSUE TITLE
Tables, diagrams not visible

### ISSUE THREAD

**Issue by gedpet1** [mwilliamson/dotnet-mammoth#4]
Greetings,

I try executing your application with the following code fragment 

```
namespace Mammoth.Cli {
	internal class Program {
		public static void Main(string[] args) {

		    var converter = new DocumentConverter();
		    var result = converter.ConvertToHtml("document.docx");
		    var html = result.Value; 
            var warnings = result.Warnings; 

            Console.WriteLine(result.Value);
		}
	}
}

```
But your application does not show tables, diagrams that were imported from word to html using your solution. They are missing in HTML

Is it a workaround while using your library? Can it show tables, diagrams and other alike components in html as well? Thank you for your response.

**Comment by mwilliamson** [comment]
Tables should work, but it depends on how they've been added to the
document. If you can provide an example document, the expected HTML,
the generated HTML and the warnings, I'll take a look when I get a
chance, but I don't know when that'll be.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything else I can do.
