### ISSUE TITLE
The Symbol corresponding to Greek letter "mu" is not interpreted

### ISSUE THREAD

**Issue by cosmin-ciuc** [mwilliamson/dotnet-mammoth#6]
Hello,

I'm using Mammoth Converter to convert Microsoft Word documents in Open XML format to HTML and I just discovered that if I use the Symbol for Greek letter "mu" (0x6D in Symbol font), this character is completely ignored by the Mammoth Converter.

I have created this sample Word document showing the case.
[Document with micro sign.docx](https://github.com/mwilliamson/dotnet-mammoth/files/2048012/Document.with.micro.sign.docx)

It seems that the XML element 
`<w:sym w:font="Symbol" w:char="006D"/>`
is completely ignored during the conversion process.

Thank you.

**Comment by mwilliamson** [comment]
Symbol elements should hopefully now be handled in the latest prerelease, `1.7.0-alpha.3`.
