### ISSUE TITLE
Preserving colors

### ISSUE THREAD

**Issue by nickpreston24** [mwilliamson/dotnet-mammoth#7]
Hello,

I'd like to preserve text colours if possible.  I know in Headers you have them ignored (lossy), but for paragraph text, I don't see it mentioned, i.e.: 

> For instance, Mammoth converts any paragraph with the style Heading 1 to h1 elements, rather than attempting to exactly copy the styling (font, text size, colour, etc.) of the heading.

If not supported, do you have any suggestions?

I found this, but it's for your npm variant:
https://npmjs.com/package/mammoth-colors

**Comment by mwilliamson** [comment]
That sentence applies to all paragraphs -- Mammoth does not attempt to copy the exact styling of elements. If you want to use Mammoth, the only suggestion I would have would to use styles rather than direct formatting.
