### ISSUE TITLE
Have I got the code right?

### ISSUE THREAD

**Issue by digitalanalogue9** [mwilliamson/dotnet-mammoth#9]
Hi
In the warnings I see 
Unrecognised paragraph style: Level 1 (Style ID: Level1)

In my code I've got
var converter = new DocumentConverter();
converter.AddStyleMap("p[style-name='Level 1'] => h1.level1");

Is my expectation correct that it should be changing all "Level 1" styled paragraphs to a H1 with a class of "level1" ?

Thanks
Dan

**Comment by mwilliamson** [comment]
Calling `AddStyleMap` creates a new document converter, rather than modifying the existing one, so you need to use the return value from `AddStyleMap`.
